{% set version = '1.4.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ottr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ottr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ottr/ottr_{{ version }}.tar.gz
  sha256: 3a4d51e49e77f2b29883be008f073bf245f47bbcdc32223c5199a4d947018172

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-jsonlite
    - r-testthat
    - r-zip
  run:
    - r-base
    - r-r6
    - r-jsonlite
    - r-testthat
    - r-zip

test:
  commands:
    - $R -e "library('ottr')"           # [not win]
    - "\"%R%\" -e \"library('ottr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ottr
  license: BSD-3-Clause
  summary: An R autograding extension for Otter-Grader (<https://otter-grader.readthedocs.io>).
    It supports grading R scripts, R Markdown documents, and R Jupyter Notebooks.
  license_family: BSD
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - chrispyles

# Package: ottr
# Title: An R Autograding Extension for Otter-Grader
# Version: 1.4.0
# Authors@R: c( person(given = "Christopher", family = "Pyles", email = "cpyles@berkeley.edu", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-8520-7593")), person(given = "UC Berkeley Data Science Education Program", role = c("cph")))
# Maintainer: Christopher Pyles <cpyles@berkeley.edu>
# Description: An R autograding extension for Otter-Grader (<https://otter-grader.readthedocs.io>). It supports grading R scripts, R Markdown documents, and R Jupyter Notebooks.
# License: BSD_3_clause + file LICENSE
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Depends: R (>= 4.0.0)
# Imports: jsonlite, testthat, tools, R6, zip, methods
# Suggests: IRdisplay, mockery, rmarkdown, stringr, withr, IRkernel
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2023-07-19 01:50:15 UTC; chrispyles
# Author: Christopher Pyles [aut, cre] (<https://orcid.org/0000-0001-8520-7593>), UC Berkeley Data Science Education Program [cph]
# Repository: CRAN
# Date/Publication: 2023-07-19 08:10:09 UTC
